//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phamtungson_2210900122_K22CNT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_hoa_don
    {
        public string ma_hd { get; set; }
        public string ma_sp { get; set; }
        public string ma_size { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> don_gia { get; set; }
        public Nullable<decimal> thanh_tien { get; set; }
    
        public virtual hoa_don hoa_don { get; set; }
        public virtual size size { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
